### ISSUE TITLE
for those who are struggling to compile 

### ISSUE THREAD

**Issue by BenBa99** [cyrusbehr/tensorrt-cpp-api#7] opened 2023-03-09 12:55 UTC
add those to CmakeLists.txt:
```# Add TensorRT library
find_path(TENSORRT_INCLUDE_DIR NvInfer.h HINTS ${CUDA_TOOLKIT_ROOT_DIR} ${CUDA_INCLUDE_DIRS})
find_library(TENSORRT_LIB nvinfer HINTS ${CUDA_TOOLKIT_ROOT_DIR} ${CUDA_LIBRARIES})
include_directories(${TENSORRT_INCLUDE_DIR})

include_directories(/usr/local/cuda/include)
include_directories(/usr/src/tensorrt/samples/common)
link_libraries(${TENSORRT_LIB})```

**Comment by cyrusbehr** [comment] 2023-03-10 21:55
Not exactly sure what the issue is here as it should have searched in the appropriate directories based on [this](https://github.com/cyrusbehr/tensorrt-cpp-api/blob/main/cmake/FindTensorRT.cmake} cmake file, but hopefully this can help other users which are also stuck. Closing this issue for now.

**Closed by cyrusbehr** 2023-03-10 21:55 UTC

**Comment by mathanprasannakumar** [comment] 2023-10-09 11:28
Hey@cyrusbehr,

while building i am getting not declared in this scope for all the cuda declarations,Please help or guide me how can i solve this .
![Screenshot from 2023-10-09 16-55-26](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/106004161/4a2f5038-a4c9-4c69-8d5e-ab96d43e01b2)

**Comment by mathanprasannakumar** [comment] 2023-10-10 16:35
@cyrusbehr I created a new issue yesterday , Please review the created issue and thanks for the reply.
